.TH SUPERKB "1" "May 2009" "superkb 0.17" "User Commands"
.SH NAME
superkb \- A hotkey-based application launcher with on-screen keyboard.
.SH DESCRIPTION
usage: superkb [options]
.SH OPTIONS
.TP
\fB\-0\fR
Quit when Superkb is ready (for timing and debugging).
.TP
\fB\-d\fR level
Show debug messages up to the specified verbosity level.
.TP
\fB\-h\fR
Shows this help.
.SH "SEE ALSO"
The full documentation for
.B superkb
and its configuration is maintained at the project website:
.IP
.B http://superkb.sourceforge.net/
.PP
