[synopsis]
superkb [options]

[=description]
Superkb is a keyboard-based application launcher based on a hotkey (the Super key by default) that allows for on-screen keyboard hints to be displayed if it is held long enough without calling any bound action. The hints will be shown in the form of icons in a keyboard.

System-wide configuration for Superkb is read from \fB/etc/superkbrc\fR. It can be extended with user-specific changes read from \fB$HOME/.superkbrc\fR.

[examples]
You should find sample files under \fB/usr/share/doc/superkb/sample-config\fR. Detailed description of the directives can be found online at the Wiki (see below).

[reporting bugs]
Bug tracker for Superkb is located at
.BR https://bugs.launchpad.net/superkb .

[more information]
The website for Superkb is located at
.B http://superkb.org/
and
there is a documentation Wiki at
.BR http://superkb.org/wiki .
