#!/bin/bash

if [ "$1" = "-v" ]; then
    VERSION=$(cut -d'"' -f2 version.h)
    VEXTRA=$(./extendedversioninfo.bash)
    echo "$(cut -d'"' -f2 version.h)${VEXTRA}"
    exit 0
fi

if [ "$1" = "-h" ]; then
    bash <(cpp -E <(cat main-help-message.h; echo "echo -e HELP_MESSAGE"))
    exit 0
fi


